### ISSUE TITLE
To use a pre-trained model in the 3-cam system

### ISSUE THREAD

**Issue by EvenGu** [spoonsso/dannce#100]
The models provided are trained on a 6-camera system but my system has only 3 cameras. Can I still reuse the weights and finetune instead of training from scratch?
Thanks! 

FYI, I have the *dannce.mat file setup. I have 8 keypoints instead of 22. I copied the DANNCE and COM folders from `demo/markerless_mouse_1` to my project folder and edited accordingly. I trained using the command
`dannce-train ..\configs\dannce_rat_config.yaml --n-views 3 --com-fromlabels true`

The reason I set the `com-fromlabels` true is because I don't know how to set values in the com3d field in the *dannce.mat file.  Without the flag, I got error message as below and basically no value to work with.
_Experiment 0 using com3d: ./rodent_label3d_dannce_1000.mat
Removed 1000 samples from the dataset because they either had COM positions over cthresh, or did not have matching sampleIDs in the COM file
Using 0 samples total._

With the flag being true, I got errors as below:
![image](https://user-images.githubusercontent.com/8534966/159842988-537258ec-47b4-4435-bf51-d7eaffa63f0c.png)

Your help will be much appreciated!

**Comment by spoonsso** [comment]
Have you made your own COM predictions yet, and do they look good? If so, I recommend using those rather than com-fromlabels. As for the 3-camera network, yes, we have 3-camera weights that you can use. See https://github.com/spoonsso/dannce/issues/62#issuecomment-893714409

**Comment by EvenGu** [comment]
Thank you. I was able to train the COM and use the 3-camera weights. You can close this issue if you want. ( I just realized that it has been reopened. )
