### ISSUE TITLE
DANNCE postprocessing analysis

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#102]
Hi! 
May I ask if your team has integrated the whole postprocessing analysis, including DANNCE and CAPTURE?
I found there are some different descriptions between DANNCE and CAPTURE which make me a bit confused, (e.g. impute method, movement threshold...). 
So I would like to know if you have any scripts for generating the behavior map based on DANNCE predicted models. Any suggestions will be appreciated. 
Many thanks!

**Comment by spoonsso** [comment]
We are actively iterating on the postprocessing analysis pipeline (mostly to make it more user-friendly and easily scalable to very large datasets), but you can refer to my CAPTURE fork for a script that will run the pipeline on DANNCE mouse data (https://github.com/spoonsso/CAPTURE_demo/blob/master/Species_specific_files/pd_analysis_demo.m). This is an example for a 20-landmark mouse dataset we are using in the lab. To use it with a 22-marker mouse dataset (i.e., like the DANNCE demo), you will need to replace all instances of `taddy_mouse` in pd_analysis_demo.m with `kyle_mouse`. Any deviations from the supported skeletons will require that you create a custom `Utility/load_*_anglestruct.m` that defines joint angles in terms of the landmarks your skeleton uses. You can see any exsample of this in https://github.com/spoonsso/CAPTURE_demo/blob/master/Utility/load_mouse_kyle_anglestruct.m
