### ISSUE TITLE
clean up camera calibration scripts

### ISSUE THREAD

**Issue by spoonsso** [spoonsso/dannce#11]
@jessedmarshall 
It looks like there are multiple copies of `multi-camera-calibration`, one in the base folder, and one in `calibration`. Can you verify that one of the copies can be deleted, and update any documentation in the README that might refer to the locations of these files.

**Comment by spoonsso** [comment]
@jessedmarshall can you take a look at this again?

**Comment by jessedmarshall** [comment]
Yes you can delete the multi-camera-calibration in the base directory. It is duplicated in calibration.
