### ISSUE TITLE
dannce-train: 6cam.hdf5 file can only used for 6 cameras finetuning, how can I finetune if I only have 2 cameras

### ISSUE THREAD

**Issue by joji2010** [spoonsso/dannce#114]
in dannce-train step, I am using weights.rat.MAX.6cam.hdf5 for finetuning.  However, I only have 2 cameras, this hdf5 file does not work.  How to create a 2cam hdf5 file?  Thank you.

**Comment by data-hound** [comment]
Hi @joji2010 

You can use `n_views:6` to train on 2 cameras with 6 cam hdf5. Please check the [wiki ](https://github.com/spoonsso/dannce/wiki/Optional-parameters-for-DANNCE#n_views) for more details.
