### ISSUE TITLE
camera angle for calibration

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#118]
Hi. I am trying to do the calibration now. But I have a question:
Is it ok if we set the camera at angles of 60 degree above about the arena? I think the angle over 45° should affect the accuracy of calibration. I wonder if >45° angle is not acceptable in the experiment. 
Please give your advice. Thank you very much.

**Comment by data-hound** [comment]
Tagging @spoonsso for the clarification.

**Comment by spoonsso** [comment]
There is no issue with calibrating at those angles. The only issue with steeper camera angles is that they may not capture the animal appendages as well (via occlusion by the body)
