### ISSUE TITLE
 3-camera COM weight network before finetune.

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#123]
Hi. I wonder where can I find the pre-trained 3-camera COM weight network before finetune. Thank you. Comments #62  has given the pre-trained 3-dannce weight, is it the same weight used in com-train and com-predict? Thank you!

**Comment by spoonsso** [comment]
The COM weights are the same for any number of cameras -- the COM net processes each view separately, one at a time. So you should be able to use the existing COM weights for this.
