### ISSUE TITLE
multiple camera caliration

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#127]
We have 6 camera system, but the problem is how to get the extrinsic matrix for all 6 cameras. 
because we cannot detect the same checkboard pattern well when we put the checkboard on the floor to make sure the whole pattern is captured by all 6 cameras. 
Are there any good suggestions? Thank you very much.

**Comment by spoonsso** [comment]
The easiest is to work out a target configuration where you can see a common set of points. We use the LFrame for this, meaning even cameras that dont have a good view of the entire floor can still see the same points as the other cameras. If you are using the checkerboard, can you move the cameras in such a way that they can all see the checkerboard on the floor?

Have you tried using the anipose calibration workflow? It should be able to calibrate bot the extrinsics and intrinsics from videos of moving your checkerboard around your field of view (although ideally it should be a ChArUco board). https://anipose.readthedocs.io/en/latest/

**Comment by yuan0821** [comment]
![cali_anipose](https://user-images.githubusercontent.com/50692530/192297769-aa219652-94fb-49d7-b057-913f2a51b907.png)
yes, I use the aniposelib to calibrate. the result format is different from that in matlab. The rotation is 3x1 which does not match dannce. 
Do you think it should be a problem to use the aniposelib in dannce? 

Thank you very much.

**Comment by Bzver** [comment]
To anyone also stumbling upon this issue, the rotation mismatch occurred because anipose uses Rvec (rotation vector, 3x1) while dannce uses a rotation matrix (3x3). However, the two can be converted to one another. Here is a conversion script in my repo which I hope will help: https://github.com/Bzver/Calibration-Transform.
