### ISSUE TITLE
How to train DANNCE with more than 6 cameras?

### ISSUE THREAD

**Issue by PIPIhuangy** [spoonsso/dannce#131]
Hi, we have a 8 cameras system, and when I was running DANNCE-train I met a problem, that is the code can only duplicate views less than 6, what can I do? Thanks!

**Comment by spoonsso** [comment]
@PIPIhuangy and I discussed this over email. The only thing you should need to do is set `n_views` to 8 and make sure that your `*dannce.mat` file contains parameters for all 8 cameras.
