### ISSUE TITLE
When running dannce-predict demo script, GPU usage is at 0%

### ISSUE THREAD

**Issue by d2ncpp** [spoonsso/dannce#134]
The dannce-predict demo script took very long than the estimated 2 minutes. Probably, mine was at least 30 minutes. I reckon only the CPU was used during the operation since it was at 100% usage. What could possibly be wrong?

**Comment by spoonsso** [comment]
This normally happens when there is an issue with your cudnn, cuda toolkit, or gpu drivers. Can you look at the program output at the start? There should be a series of messages about successfully (or unsuccessfully) finding necessary cuda dlls.
