### ISSUE TITLE
how to use rats16.mat skeleton for CAPTURE_demo analysis

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#142]
Hi, I work smoothly on the DANNCE training and prediction. However, struggled with the next steps. any suggestion would be appreciated. 

1. After labelling 16 key points using rats16.mat skeleton, how to use the generated prediction.mat file for further CAPTURE_demo analysis. Because I find in the CAPTURE_demo, it is the 20 key points based on jesse_skeleton.mat skeleton were used. There are some key points like 'ElbowR','ArmR' when extracting supervised features.  **I wonder if there is any suggestions or CAPTURE scripts I could use after DANNCE training with 16 keypoints.**

2. when performing CAPTURE cluster, I want to know if it must **hand-label one behavioral category for each cluster** (i.e., for 1830 clusters) by myself. is there any good suggestions?

**Comment by spoonsso** [comment]
@yuan0821 you can try https://github.com/joshuahwu/dappy -- this is a python framework based on CAPTURE with a tutorial that explains how to use different skeletons.
