### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#143]
Hi, I get instinct parameters from Matlab Calibration App, and each projection error is less than 0.3. 

Then I use the instinct params to do the extrinsic calibration. I getpts 14 points in the same checkboard pattern between all cameras. Then I can get the rotation matrices and translation vectors after running the following code.
the code is based on the [dannce](https://github.com/spoonsso/dannce/tree/release_dev2)/[calibration](https://github.com/spoonsso/dannce/tree/release_dev2/calibration)/[multi-camera calibration](https://github.com/spoonsso/dannce/tree/release_dev2/calibration/multi-camera%20calibration)/calibration_extrinsic_Lframe.m.

Is it already enough to do hand-labeled markers then? In my experience, the result of hand-labeled is fine. 
But I just found in your public script [dannce](https://github.com/spoonsso/dannce/tree/release_dev2)/[calibration](https://github.com/spoonsso/dannce/tree/release_dev2/calibration)/acquire_calibration_3cam_mouse_clean.m,
you also performed STEP 6 - refine with checkerboard and  STEP 7 compute the corrected world coordinates.
I am confused why you perform steps 6 and 7.

Thank you very much @davidhildebrand .

**Comment by spoonsso** [comment]
Steps 6 & 7 are optional and only need to be used if your calibration fit is subpar.
