### ISSUE TITLE
How to Interpret Data Generated from Quickstart Demo

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#40]
I successfully completed the steps on the DANNCE README regarding the Quickstart Demo, and new files were generated. However, the instructions for the Quickstart Demo do not explain how to read or interpret the results. Can you please provide more information or a link on this?

**Comment by spoonsso** [comment]
I just added a page to the wiki explaining all generated files for `dannce-train`, `dannce-predict`, `com-train`, and `com-predict`. https://github.com/spoonsso/dannce/wiki/Output-Documentation .

Please let me know if you have any other questions.
