### ISSUE TITLE
CUDA runtime implicit initialization on GPU:0 failed Status: device kernel image is invalid.

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#41]
hi!!
i met a dannce version issue. it fail to run dannce-predict ../../configs/dannce_mouse_config.yaml. 
the error is: 
**tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid.**

is there any conflicts between  cuda and tenserflow? which version is fit with dannce 1.1.0??
cudatoolkit               10.1.243             h036e899_8    conda-forge
cudnn                     7.6.5.32             hc0a50b0_1    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
pytorch                   1.7.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
tensorflow                2.3.0                    pypi_0    pypi

please kindly advice me how to fix it. many thanks!!!!

**Comment by spoonsso** [comment]
I have essentially the same cuda/tensorflow combo (my tensorflow is 2.3.1 but I doubt that matters). What operating system are you using? What GPU are you using? Does `nvidia-smi` produce a valid output? Can you run other tensorflow code?

[Discussion around this tensorflow issue](https://github.com/tensorflow/tensorflow/issues/41990) suggests that TF 2.3 might not be compatible with certain GPUs. Although it looks like downgrading to TF 2.2 might work.

**Comment by spoonsso** [comment]
@yuan0821 any luck?

**Comment by yuan0821** [comment]
Oh!! thanks a lot! and sorry for late reply! i have fixed it already. my computer system is Ubuntu 18.0, and the GPU is RTX3070. The cuda > 11., so the trick is to get the cudatoolkit 11.0.3 with pytorch 1.7. @spoonsso

**Comment by cirongliu** [comment]
> Oh!! thanks a lot! and sorry for late reply! i have fixed it already. my computer system is Ubuntu 18.0, and the GPU is RTX3070. The cuda > 11., so the trick is to get the cudatoolkit 11.0.3 with pytorch 1.7. @spoonsso

Hi，Could you mind providing details about how to make it work on GPU RTX30xx.

I got a RTX3090 (30xx required tf2.4 and above), but it seems that DANNCE only works on tf 2.3.1.

How you make the DANNCE work on your hardware and CUDA11.

Thanks!

**Comment by cxrodgers** [comment]
I am also having this issue with RTX3060, tf 2.3.1, cudatoolkit 10.1. Seems like it might be an RTX* issue since everyone in this thread has one? Did anyone find a combination of versions that works?

Trying to use the suggestion from @yuan0821 to use cudatoolkit 11.0.3 and pytorch 1.7 but having some  trouble getting this to work with conda. 

thanks!

**Comment by xman3911** [comment]
I have the same issue because the Torch and TensorFlow/CUDA are installed in the same env. it just works when I uninstall the Torch.
