### ISSUE TITLE
Pose Estimation Using DANNCE

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#42]
In the paper on DANNCE, specific poses are able to be identified. However, I do not see any information regarding poses in any of the files generated for the DANNCE demo. Could you give me instructions on how to generate and interpret rodent poses using DANNCE?

**Comment by spoonsso** [comment]
Hello, thank you for interest in our tools! 

The poses can be embedded and clustered using the code from https://github.com/jessedmarshall/CAPTURE_demo. There should be an option to selected "kyle_mouse" as an skeleton type, which will be compatible with the demo data. Embedding and clustering will work best if you predict over at least 30 minutes of video. @jessedmarshall might also have some other tips. And if you have more specific questions about the CAPTURE_demo code, we are happy to help.
