### ISSUE TITLE
Importing Experimental predictions.mat Data into CAPTURE_demo

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#47]
Hello, I am referring back to Issue #43 , predictions.mat File in CAPTURE_demo Code. It was mentioned that the predictions.mat file generated from the demo could not be imported into the CAPTURE_demo code, and I had to download another demo predictions file for the CAPTURE_demo code to run. I have looked at other pose-estimation software, but they can not accommodate the three-dimensional nature of the predictions from DANNCE. If you could work on or provide the Bash script that executes dannce-predict followed by makeStructuredDataNoMocap.py so that experimental predictions data from DANNCE can be interpreted, that would be appreciated!

**Comment by spoonsso** [comment]
In 91c6a84, I added bash script in `demo/markerless_mouse_1` that runs `dannce-predict` followed by `makeStructuredDataNoMocap.py`. `makeStructuredDataNoMocap.py` requires a reference skeleton file, which I have also added to `configs/mouse22_skeleton.mat`. If you are working with a different skeleton, you will need to make your own skeleton file, which defines the names of each joint, their linkages (e.g. EarL linked to EarR), and colors for plotting each joint (used by Label3D).
