### ISSUE TITLE
User-Specific Drives and Files in CAPTURE_demo Code

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#48]
I was going through the CAPTURE_demo code, and I noticed that a few variables were defined by files that were obtained from user-specific paths (Jesse). If you could either update these variables with files that can be accessed by any user or tell me how to generate these files using either demo or experimental data, I would really appreciate it. I am not going to be using birds, so if you do not update the variables that are defined by user-specific paths in the files for analyzing birds, that is fine. Below is a list of the scripts that contain paths to user-specific paths. Each script is classified under the CAPTURE_demo folder it is in. 

Animating:
dannce_reprojection_sbys_bird_demo.m
plot_frame_dannce_reprojection_multi_bird_demo.m

Behavioral_analysis:
get_supervised_features_demo.m
demoreembed.m

Preprocessing:
preprocess_dannce.m
In preprocess_dannce.m, a user-specific pathway loads a predictions.mat file. Should this be changed to the pathway that leads to the predictions.mat file generated by either the demo or an experiment?

Utlity:
load_bird_anglestruct.m
load_link_files.m 
The user-specific pathway in load_link_files.m is under the case for birds, so if you don't update it, that is fine.

VideoAnalysis:
demo_readinimageframes.m

**Comment by spoonsso** [comment]
I copied this issue over to CAPTURE_demo and will answer there.
