### ISSUE TITLE
Visualise pose prediction 

### ISSUE THREAD

**Issue by enajx** [spoonsso/dannce#51]
Hi, I'm following the 'get started' demo, however it abruptly stops after generating `save_data_AVG0.mat`. It'd be great if you could add the missing steps to generate the [examples](https://github.com/spoonsso/dannce#mouse) shown in the readme.

**Comment by spoonsso** [comment]
Hi Elias,

You can use the View3D function of Label3D package to do that. Check out
`example.m` @ https://github.com/diegoaldarondo/Label3D.



Please let me know if you have any other questions.

**Comment by enajx** [comment]
Perfect, thank you!
