### ISSUE TITLE
KeyError: 'com' during dannce-train

### ISSUE THREAD

**Issue by harshk95** [spoonsso/dannce#55]
Hi,
Upon starting dannce train we get the following error. The com prediction completed successfully and the com3d file has been generated in the ./COM/predict_results

> (dannce) E:\DANNCE_test_210608>dannce-train C:\Users\realtime\dannce\configs\dannce_mouse_config.yaml
> 2021-07-14 14:00:37.660334: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
> io_config not found in io.yaml file, falling back to main config
> new_n_channels_out not found in io.yaml file, falling back to main config
> batch_size not found in io.yaml file, falling back to main config
> epochs not found in io.yaml file, falling back to main config
> net_type not found in io.yaml file, falling back to main config
> train_mode not found in io.yaml file, falling back to main config
> num_validation_per_exp not found in io.yaml file, falling back to main config
> vol_size not found in io.yaml file, falling back to main config
> nvox not found in io.yaml file, falling back to main config
> max_num_samples not found in io.yaml file, falling back to main config
> dannce_finetune_weights not found in io.yaml file, falling back to main config
> mono not found in io.yaml file, falling back to main config
> com_train_dir set to: .\COM\train_results\
> com_predict_dir set to: .\COM\predict_results\
> dannce_train_dir set to: .\DANNCE\train_results\AVG\
> dannce_predict_dir set to: .\DANNCE\predict_results\
> dannce_predict_model set to: .\DANNCE\train_results\AVG\weights.1200-12.77642.hdf5
> exp set to: [{'label3d_file': 'E:/DANNCE_test_210608/20210610_091000_Label3D_dannce.mat'}]
> io_config set to: io.yaml
> new_n_channels_out set to: 22
> batch_size set to: 4
> epochs set to: 1200
> net_type set to: AVG
> train_mode set to: finetune
> num_validation_per_exp set to: 4
> vol_size set to: 100
> nvox set to: 64
> max_num_samples set to: max
> dannce_finetune_weights set to: C:\Users\realtime\dannce\demo\markerless_mouse_1\DANNCE\train_results
> mono set to: True
> base_config set to: C:\Users\realtime\dannce\configs\dannce_mouse_config.yaml
> viddir set to: videos
> crop_height set to: None
> crop_width set to: None
> camnames set to: None
> n_channels_out set to: 20
> sigma set to: 10
> verbose set to: 1
> net set to: None
> gpu_id set to: 0
> immode set to: vid
> mirror set to: False
> loss set to: mask_nan_keep_loss
> num_train_per_exp set to: None
> metric set to: ['euclidean_distance_3D']
> lr set to: 0.001
> augment_hue set to: False
> augment_brightness set to: False
> augment_hue_val set to: 0.05
> augment_bright_val set to: 0.05
> augment_rotation_val set to: 5
> data_split_seed set to: None
> valid_exp set to: None
> com_fromlabels set to: False
> medfilt_window set to: None
> com_file set to: None
> new_last_kernel_size set to: [3, 3, 3]
> n_layers_locked set to: 2
> vmin set to: None
> vmax set to: None
> interp set to: nearest
> depth set to: False
> comthresh set to: 0
> weighted set to: False
> com_method set to: median
> cthresh set to: None
> channel_combo set to: None
> predict_mode set to: torch
> n_views set to: 6
> rotate set to: True
> augment_continuous_rotation set to: False
> drop_landmark set to: None
> use_npy set to: False
> rand_view_replace set to: True
> n_rand_views set to: 0
> multi_gpu_train set to: False
> start_batch set to: 0
> n_channels_in set to: None
> extension set to: None
> vid_dir_flag set to: None
> chunks set to: None
> lockfirst set to: None
> load_valid set to: None
> raw_im_h set to: None
> raw_im_w set to: None
> n_instances set to: 1
> start_sample set to: None
> write_npy set to: None
> expval set to: None
> com_thresh set to: None
> cam3_train set to: None
> debug_volume_tifdir set to: None
> downfac set to: None
> from_weights set to: None
> dannce_predict_vol_tifdir set to: None
> Using the following *dannce.mat files: .\20210610_091000_Label3D_dannce.mat
> Setting vid_dir_flag to True.
> Setting extension to .avi.
> Setting chunks to {'Camera1': array([0]), 'Camera2': array([0]), 'Camera3': array([0]), 'Camera4': array([0]), 'Camera5': array([0])}.
> Setting n_channels_in to 3.
> Setting raw_im_h to 600.
> Setting raw_im_w to 960.
> Setting expval to True.
> Setting net to finetune_AVG.
> Setting crop_height to [0, 600].
> Setting crop_width to [0, 960].
> Setting maxbatch to max.
> Setting start_batch to 0.
> Setting vmin to -50.0.
> Setting vmax to 50.0.
> Fine-tuning from C:\Users\realtime\dannce\demo\markerless_mouse_1\DANNCE\train_results\weights.12000-0.00014.hdf5
> Experiment 0 using videos in E:/DANNCE_test_210608\videos
> Experiment 0 using camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5']
> {'0_Camera1': array([0]), '0_Camera2': array([0]), '0_Camera3': array([0]), '0_Camera4': array([0]), '0_Camera5': array([0])}
> E:/DANNCE_test_210608/20210610_091000_Label3D_dannce.mat
> The length of the camnames list must divide evenly into 6. Duplicate a subset of the views starting from the first camera (y/n)?y
> Duping camnames. Changed from ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5'] to ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5', 'Camera1']
> Traceback (most recent call last):
>   File "C:\Users\realtime\anaconda3\envs\dannce\Scripts\dannce-train-script.py", line 33, in <module>
>     sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-train')())
>   File "c:\users\realtime\dannce\dannce\cli.py", line 66, in dannce_train_cli
>     dannce_train(params)
>   File "c:\users\realtime\dannce\dannce\interface.py", line 737, in dannce_train
>     ) = do_COM_load(exp, expdict, n_views, e, params)
>   File "c:\users\realtime\dannce\dannce\interface.py", line 1685, in do_COM_load
>     c3dfile = io.load_com(exp["com_file"])
>   File "c:\users\realtime\dannce\dannce\engine\io.py", line 91, in load_com
>     d = sio.loadmat(path)["com"]
> KeyError: 'com'

Thanks for the help!

**Comment by diegoaldarondo** [comment]
You can specify the com_file used for prediction in the io.yaml.

`com_file: /path/to/com3d.mat`

**Comment by harshk95** [comment]
Hey,
same error even if I add the line specified above. I have attached the io.yaml I used and the config file.

[io.txt](https://github.com/spoonsso/dannce/files/6817668/io.txt)
[dannce_mouse_config.txt](https://github.com/spoonsso/dannce/files/6817669/dannce_mouse_config.txt)
![Screencap](https://user-images.githubusercontent.com/42764867/125660786-af4d0eab-f58c-45be-8561-3461bf2c9401.PNG)

> 2021-07-14 18:42:27.600576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
> io_config not found in io.yaml file, falling back to main config
> new_n_channels_out not found in io.yaml file, falling back to main config
> batch_size not found in io.yaml file, falling back to main config
> epochs not found in io.yaml file, falling back to main config
> net_type not found in io.yaml file, falling back to main config
> train_mode not found in io.yaml file, falling back to main config
> num_validation_per_exp not found in io.yaml file, falling back to main config
> vol_size not found in io.yaml file, falling back to main config
> nvox not found in io.yaml file, falling back to main config
> max_num_samples not found in io.yaml file, falling back to main config
> dannce_finetune_weights not found in io.yaml file, falling back to main config
> mono not found in io.yaml file, falling back to main config
> com_train_dir set to: .\COM\train_results\
> com_file set to: E:\DANNCE_test_210608\COM\predict_results\com3d.mat
> dannce_train_dir set to: .\DANNCE\train_results\AVG\
> dannce_predict_dir set to: .\DANNCE\predict_results\
> dannce_predict_model set to: .\DANNCE\train_results\AVG\weights.1200-12.77642.hdf5
> exp set to: [{'label3d_file': 'E:/DANNCE_test_210608/20210610_091000_Label3D_dannce.mat'}]
> io_config set to: io.yaml
> new_n_channels_out set to: 22
> batch_size set to: 4
> epochs set to: 1200
> net_type set to: AVG
> train_mode set to: finetune
> num_validation_per_exp set to: 4
> vol_size set to: 100
> nvox set to: 64
> max_num_samples set to: max
> dannce_finetune_weights set to: C:\Users\realtime\dannce\demo\markerless_mouse_1\DANNCE\train_results
> mono set to: True
> base_config set to: C:\Users\realtime\dannce\configs\dannce_mouse_config.yaml
> viddir set to: videos
> crop_height set to: None
> crop_width set to: None
> camnames set to: None
> n_channels_out set to: 20
> sigma set to: 10
> verbose set to: 1
> net set to: None
> gpu_id set to: 0
> immode set to: vid
> mirror set to: False
> loss set to: mask_nan_keep_loss
> num_train_per_exp set to: None
> metric set to: ['euclidean_distance_3D']
> lr set to: 0.001
> augment_hue set to: False
> augment_brightness set to: False
> augment_hue_val set to: 0.05
> augment_bright_val set to: 0.05
> augment_rotation_val set to: 5
> data_split_seed set to: None
> valid_exp set to: None
> com_fromlabels set to: False
> medfilt_window set to: None
> new_last_kernel_size set to: [3, 3, 3]
> n_layers_locked set to: 2
> vmin set to: None
> vmax set to: None
> interp set to: nearest
> depth set to: False
> comthresh set to: 0
> weighted set to: False
> com_method set to: median
> cthresh set to: None
> channel_combo set to: None
> predict_mode set to: torch
> n_views set to: 6
> rotate set to: True
> augment_continuous_rotation set to: False
> drop_landmark set to: None
> use_npy set to: False
> rand_view_replace set to: True
> n_rand_views set to: 0
> multi_gpu_train set to: False
> start_batch set to: 0
> n_channels_in set to: None
> extension set to: None
> vid_dir_flag set to: None
> chunks set to: None
> lockfirst set to: None
> load_valid set to: None
> raw_im_h set to: None
> raw_im_w set to: None
> n_instances set to: 1
> start_sample set to: None
> write_npy set to: None
> expval set to: None
> com_thresh set to: None
> cam3_train set to: None
> debug_volume_tifdir set to: None
> downfac set to: None
> from_weights set to: None
> dannce_predict_vol_tifdir set to: None
> Using the following *dannce.mat files: .\20210610_091000_Label3D_dannce.mat
> Setting vid_dir_flag to True.
> Setting extension to .avi.
> Setting chunks to {'Camera1': array([0]), 'Camera2': array([0]), 'Camera3': array([0]), 'Camera4': array([0]), 'Camera5': array([0])}.
> Setting n_channels_in to 3.
> Setting raw_im_h to 600.
> Setting raw_im_w to 960.
> Setting expval to True.
> Setting net to finetune_AVG.
> Setting crop_height to [0, 600].
> Setting crop_width to [0, 960].
> Setting maxbatch to max.
> Setting start_batch to 0.
> Setting vmin to -50.0.
> Setting vmax to 50.0.
> Fine-tuning from C:\Users\realtime\dannce\demo\markerless_mouse_1\DANNCE\train_results\weights.12000-0.00014.hdf5
> Experiment 0 using videos in E:/DANNCE_test_210608\videos
> Experiment 0 using camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5']
> {'0_Camera1': array([0]), '0_Camera2': array([0]), '0_Camera3': array([0]), '0_Camera4': array([0]), '0_Camera5': array([0])}
> E:/DANNCE_test_210608/20210610_091000_Label3D_dannce.mat
> The length of the camnames list must divide evenly into 6. Duplicate a subset of the views starting from the first camera (y/n)?y
> Duping camnames. Changed from ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5'] to ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5', 'Camera1']
> Traceback (most recent call last):
>   File "C:\Users\realtime\anaconda3\envs\dannce\Scripts\dannce-train-script.py", line 33, in <module>
>     sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-train')())
>   File "c:\users\realtime\dannce\dannce\cli.py", line 66, in dannce_train_cli
>     dannce_train(params)
>   File "c:\users\realtime\dannce\dannce\interface.py", line 737, in dannce_train
>     ) = do_COM_load(exp, expdict, n_views, e, params)
>   File "c:\users\realtime\dannce\dannce\interface.py", line 1685, in do_COM_load
>     c3dfile = io.load_com(exp["com_file"])
>   File "c:\users\realtime\dannce\dannce\engine\io.py", line 91, in load_com
>     d = sio.loadmat(path)["com"]
> KeyError: 'com'
> 

Thanks!

**Comment by diegoaldarondo** [comment]
Sorry about that, I misread and thought you were doing prediction. For training you can add the same `com_file: ...` line to the experiment dictionary in the io.yaml like this:
```
...
exp:
    - label3d_file: 'E:/DANNCE_test_210608/20210610_091000_Label3D_dannce.mat'
      com_file: E:/DANNCE_test_210608/COM/predict_results/com3d.mat
```
Keep the other line though, because you'll eventually need it for prediction.
