### ISSUE TITLE
Wand Calibration

### ISSUE THREAD

**Issue by KenR22** [spoonsso/dannce#56]
Hi,

I was wondering what would the best software be to use wand calibration and put it in a format that can be used with DANNCE.

Thanks!

**Comment by spoonsso** [comment]
In the dannce repo [calibration folder](https://github.com/spoonsso/dannce/tree/master/calibration) we have Matlab code examples for performing wand calibration. Other users use the Matlab calibration app. [anipose](https://github.com/lambdaloop/anipose) also has some nice code for calibration with ChArUco board wands.
