### ISSUE TITLE
Fast Playback Speed when Recording Videos

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#57]
Hello! I have been using part of the script acquire_calibration_3cam_mouse_clean.mat, the DANNCE camera calibration code, to record videos. However, I notice that the playback speed for these videos is faster than the speed at which the videos are supposed to be recording. I am using a Windows machine, and I can play my videos on VLC Media Player and Windows Media Player. Is there anything I can adjust in the code so that when I put a stopwatch in the arena, it takes one second in the video for one second to pass on the stopwatch? I am using three FLIR Blackfly S cameras, and my code is below. 

imaqreset
numcams = 3;
vid = cell(1,numcams);
logfile = cell(1,numcams);

parentpath = 'D:\Camera_Videos\7_21_stopwatch';
numframes_aq = 1000;

logfile_tag = 'videofiles_run1'; 
lframe_tag = 'lframe_labels';

for kk = 1:numcams
    
    vid{kk} = videoinput('gentl', kk,'Mono8');
   
    src = getselectedsource(vid{kk});
    src.GainAuto = 'Off';
    src.GammaEnable = 'True';
    src.ExposureAuto = 'Off';
    src.AcquisitionFrameRateEnable ='True';
    src.AcquisitionFrameRate = 80;

    if kk ==1
        
        src.Gain = 18.06;
        src.Gamma = 0.8;
        src.ExposureTime = 59275; 

    end
    if kk == 2
        src.Gain = 17.97;
        src.Gamma = 0.8;
        src.ExposureTime = 60111; 
    end
    if kk == 3
        src.Gain = 11.82; 
        src.Gamma = 0.8;
        src.ExposureTime = 2831;
    end
    
    vid{kk}.FramesPerTrigger = 1; 
     vid{kk}.TriggerRepeat = 999; %1000
    
    triggerconfig(vid{kk}, 'manual')
    
    vid{kk}.ReturnedColorspace = 'rgb';
    set(vid{kk}, 'LoggingMode', 'Disk&Memory');
    logfile_names{kk} = strcat(parentpath,filesep,logfile_tag,num2str(kk),'.avi');
    logfile{kk} = VideoWriter(logfile_names{kk});
    
    
    vid{kk}.DiskLogger = logfile{kk};
    open(logfile{kk})
    start(vid{kk})
    
end

for ll =1:numframes_aq
    fprintf('triggering \n')
    for kk = 1:numcams
    trigger(vid{kk})
    end
    
    pause(0.5)
end

frame_image = cell(1,numcams);

for kk = 1:numcams    
     frame_image{kk} = getsnapshot(vid{kk});
     close(logfile{kk})
end

lframename = strcat(parentpath,filesep,lframe_tag,'.mat');
 save(lframename,'frame_image');

**Comment by spoonsso** [comment]
You can set the output frame rate of a VideoWriter object using the `FrameRate` property. I am not sure whether that plays nicely with a videoinput object, but it's worth a shot.

After https://github.com/spoonsso/dannce/blob/cefd782aee1fce2044c7cef6237dfc207034fc68/calibration/acquire_calibration_3cam_mouse_clean.m#L51

try adding

`logfile{kk}.FrameRate = src.AcquisitionFrameRate`

**Comment by verpeutlab** [comment]
Thank you for letting me know about this! I will let you know how this works when I take a new calibration.
