### ISSUE TITLE
Distances between Cameras and Arena Floor/Walls

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#58]
Hello! I was looking over the methods section of the DANNCE paper, and I was just wondering about a couple distances that I wanted to take into consideration while recording data. Can you tell me what the average distance was between the camera and the floor of the arena, as well as the average distance between a camera and the sides of the arena? Thank you!

**Comment by spoonsso** [comment]
@jessedmarshall?

**Comment by jessedmarshall** [comment]
Apologies for the late reply. We have run in many different configurations, and there is no right or wrong way to set up the cameras. In the bird experiment the cameras were essentially at the walls with fisheye lenses, while in the rat experiment they were 6 feet away. Some general principles

(1) It is helpful if the animal is visible in each of the cameras at all time
(2) I would try to not use an ultrafisheye lens, as I would worry about higher order distortion terms (although to date this hasn't been a problem)
(3) The resolution in fine tuning experiments is often limited by the ability to label points by hand, so use the ability to hand label as the goal for pixel resolution.
(4) many different views and angles can work well. 

let me know if I can help more!
