### ISSUE TITLE
Support for tf 2.4 and above (for 30xx GPU)

### ISSUE THREAD

**Issue by cirongliu** [spoonsso/dannce#61]
Dear developer of Dannce,

The 3090/3080 etc. Nvidia GPUs are only working on tf 2.4 and above （CUDA 11 and above）.

However, for the Dannce, the tf 2.3 is required.

Is it possible to provide support for tf 2.4, so that people could use the lastest GPU to run Dannce.

Thanks!

**Comment by spoonsso** [comment]
Yes, we are testing this now. Stay tuned!
