### ISSUE TITLE
Error Running DANNCE with Three Cameras

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#63]
Hello! I am currently trying to execute DANNCE with the videos from three cameras. The cameras are already calibrated. I have also created a folder that contains the COM and DANNCE folders from markerless_mouse_1, the videos folder that is formatted in the layout indicated in the DANNCE READ.me file and contains the videos from all three cameras, and the label3d_dannce.mat file in the demo folder in DANNCE. 

When I input the command to run DANNCE in the command window, the program cannot be completely executed because the following message appears: **ValueError: generator already executing**. I was looking through the code in the command window that led up to this error, and the section pasted below caught my attention. 

Do you have any advice on how I can successfully run DANNCE with three cameras? Thank you!

**Code pasted from Command Window:**

Initializing Network...
Loading model from .\DANNCE\train_results\AVG\weights.1200-12.77642.hdf5
max
2250
Predicting on batch 0
c:\users\verpeutlab\desktop\dannce\dannce\engine\generator.py:975: UserWarning: Note: ignoring dimension mismatch in 3D labels
  warnings.warn(msg)
Loading new video: videos\Camera1\0.mp4 for 0_Camera1
Loading new video: videos\Camera2\0.mp4 for 0_Camera2
Loading new video: videos\Camera1\0.mp4 for 0_Camera1
Loading new video: videos\Camera3\0.mp4 for 0_Camera3
Loading new video: videos\Camera2\0.mp4 for 0_Camera2
Loading new video: videos\Camera3\0.mp4 for 0_Camera3
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [9,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [10,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

**Comment by verpeutlab** [comment]
I have been able to make some small changes to the code so that I no longer have the issue with duplicate cameras. However, I am still getting the same error with pytorch. Do you have any advice on what parameters need to be adjusted? A quick Google search indicated that I might have the wrong number of classes set, but I am not sure what they are referring to.

C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [8,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [9,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [1289,0,0], thread: [10,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.

**Comment by spoonsso** [comment]
Hi @verpeutlab. Check out Issue #62. I think the best solution would be to use one of the pre-trained 3 camera networks.
