### ISSUE TITLE
demo data illustrating the effect of saline vehicle, caffeine and amphetamine on the mouse behaviours

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#64]
May I please ask whether we could get your demo experiment data which was used to illustrate the effect of saline vehicle, caffeine and amphetamine on the mouse behaviours in the long-time scale? Thank you very much for your attention. I'm looking forward to your reply.

**Comment by spoonsso** [comment]
We didn't do any drug experiments on mice in the DANNCE paper. I assume you are thinking about the (rat) experiments in @jessedmarshall's CAPTURE paper. You should contact him directly for those data.
