### ISSUE TITLE
Geneating video with skeleton overlayed 

### ISSUE THREAD

**Issue by harshk95** [spoonsso/dannce#70]
Hi!
I was wondering if I could generate a video clip with the skeleton overlayed to get an idea of the performance of the network as in the supplementary video. Is there a tool as a part of the package and if not could you please give some pointers as to how this may be achieved.

Thanks!

**Comment by spoonsso** [comment]
Hi, @harshk95 . You can use the "View3D" option inside Label3D -- please see the Label3D (https://github.com/diegoaldarondo/label3d) docs for more detail.
