### ISSUE TITLE
 parameters when preprocessing the dance data for a mouse

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#71]
Hi Tim and Jesse, could you please help to explain the parameters when preprocessing the dance data for a mouse? 
because I am not sure the unit of these measurements and the corresponding values for a mouse, rather than a rat.
Thank you very much for your attention. 

preprocessing_parameters.median_filt_length = 3;
preprocessing_parameters.bad_frame_vel_thresh **= ??**
preprocessing_parameters.bad_frame_surround_flag = 0;
preprocessing_parameters.bad_frame_surround_number = 1;
%% preprocessing_parameters.interpolation_max_length = 5;
preprocessing_parameters.meanvelocity_lowpass = 60;
preprocessing_parameters.meanvelocity_lowpass = 60;
preprocessing_parameters.fastvelocity_threshold **=??** 
preprocessing_parameters.moving_threshold **= ??**
preprocessing_parameters.moving_framewindow **=??**

**Comment by spoonsso** [comment]
Hi @yuan0821. I believe the unit of measurements are in mm / frame, but @jessedmarshall would be the one to ask. I know you asked here, but you might try posting an issue on the CAPTURE repository, or e-mailing Jesse directly.
