### ISSUE TITLE
How to Calibrate Using DANNCE

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#72]
Hello! I am reaching out to ask for a detailed process on how to calibrate the cameras in DANNCE using the script titled acquire_calibration_3cam_mouse_clean. I have performed many trials in order to calibrate the cameras in my open field, but I am not sure how the checkerboard and the lframe should be placed in order for the script acquire_calibration_3cam_mouse_clean to run successfully or for the reprojected points to be identical to the detected points on all three cameras.  

I also have been getting an error when labeling the points on my lframe on the image from the final camera view in Step 4 of acquire_calibration_3cam_mouse_clean. So, I have restructured the script so that I have been placing the checkerboard directly in front of each camera when the 100 frames are taken (I then move it so that it is in the front of another camera when another set of 100 frames is acquired), and I have been doing the same with the lframe when the first shot of the lframe is taken. I then place the checkerboard and the lframe in the center of the arena for the next shots of the checkerboard and lframe.  These changes enable my reprojected points to be practically identical to my detected points when an image of the checkerboard appears in the code corresponding to Step 3 in acquire_calibration_3cam_mouse_clean. My script omits Steps 5 and 6 of acquire_calibration_3cam_mouse_clean. My arena has a plexiglass cylinder in it, which should be removed for the calibration, according to the instructions on the main page. 

Could you describe how to successfully calibrate the cameras in an open field with an arena lined with a plexiglass cylinder?

**Comment by spoonsso** [comment]
Can you explain a bit more about what is going wrong? So your intrinsic calibration is working well it seems -- since you say that the checkerboard points have low reprojection error? Is it the L-Frame extrinsic calibration that is failing? Are you getting to the point where you click on points on the L-Frame? If so, what do the L-Frame reprojections look like?

**Comment by verpeutlab** [comment]
Yes, I am at that part where I am clicking on the points on the L-Frame. I am able to add four points to the L-Frame image from each camera, but after I add the final point on the image that corresponds to the last camera, the code stops and I get an error message.

**Comment by spoonsso** [comment]
Can you please post your full error message here? I can help resolve the issue.

**Comment by spoonsso** [comment]
@verpeutlab closing for now. Happy to help if you provide the full error message.
