### ISSUE TITLE
Folders and Documents Generated after Training DANNCE

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#73]
Hello, I am inquiring about the folders and documents that were generated in a project's train_results folder after I executed the commands under the headings titled "Training and Predicting with the COMfinder U-Net" and "Training and Predicting with DANNCE" on the DANNCE GitHub homepage. I have attached an image of the documents and folders that have been created. Can you please tell me how to continue setting up DANNCE with these items?
![new train_results documents](https://user-images.githubusercontent.com/84207044/136850644-2bbbc59c-e545-4e7c-bddd-3a822fe909bc.PNG)

**Comment by spoonsso** [comment]
You should be able to find this info in the Wiki (https://github.com/spoonsso/dannce/wiki/Output-Documentation). But please let me know if something is missing from there.
