### ISSUE TITLE
How to deal with frames without animal?

### ISSUE THREAD

**Issue by kantkantwuqh** [spoonsso/dannce#77]
Hi,
In my animal videos there are many frames without animal, do I need to filter these frames? 
When Label3D has selected a frame without animal for me to label, can I directly skip to the next frame? 
Will these animal-free frames affect COM and DANNCE?

Thank you!

**Comment by spoonsso** [comment]
For the Label3D, you can definitely just skip ahead to a frame where you can see the animal. If the frame without an animal is left unlabeled, then it will have NaN for labels, which will be ignored by `com-train` and `dannce-train`. Ideally, though, the unlabeled frame indices would be scrubbed from the Label3D output entirely. @diegoaldarondo, is there already a Label3D method to discard unlabeled frames entirely before generating a final `label3d_dannce.mat`? 

So, COM and DANNCE training will be unaffected. For COM and DANNCE prediction, it depends on whether the animal is missing in all camera simultaneously or whether it is missing only from a subset of cameras. 

For the simultaneous missing case, you have a couple options: 1) If you are able to identify all of the frames where the animal is missing (or partially out of the frame, as DANNCE's holistic inference is unlikely to work well with only part of the animal visible), then you can remove these frames from the `sync` variable in `label3d_dannce.mat`. If you do this, those removed frames will never be evaluated by COM or DANNCE. 2) If you do not remove the missing animal frames, then COM and DANNCE will make weird predictions on those frames, but these frames can be removed from the predicted traces at the end by using either a) a threshold on velocity in the predicted traces (weird, noisy predictions will have high velocities), or b) a threshold on `pmax`, which is the peak value of the predicted 3D output maps. Another solution could be to try and remove these frames from the predicted COM traces during `dannce-predict` using the available `cthresh` and `comthresh` configuration parameters. `cthresh` will discard frames with 3D COMs outside set physical bounds (in millimeters) -- which happens in the case of noisy predictions. `comthresh` will discard specific camera views using a threshold on the max value of each view's 2D output maps. 

For the missing from a subset of cameras case, option 1 above will also work well -- i.e., remove all frames in which the animal is missing from at least 1 view. YMMY for the other options, and it depends on exactly how many views are missing the animal.

**Comment by diegoaldarondo** [comment]
Yes, unlabeled frames are left out automatically.

**Comment by kantkantwuqh** [comment]
Thank you @spoonsso ,@diegoaldarondo ! I'll try!
