### ISSUE TITLE
Follow Up to Issue #75

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#78]
Hello, I am just following up to the question I asked in issue #75 "Number of Predictions in COM." How was the program able to make predictions across all 18000 frames in markerless_mouse_1 if the COM file was only generated across 100 frames? For future data, do I just need to predict over a few frames, or is there another file with the predictions over the rest of the 18000 frames from markerless_mouse_1?

**Comment by spoonsso** [comment]
You need a COM prediction for every frame. I'm not sure what order you ran things, but the `label3d_dannce.mat` file already comes with 18000 COM predictions inside of it, so it can be used to run a full set of DANNCE predictions without running COM over the full movie. When working with real data, you will need to make sure there is a COM prediction for every frame.
