### ISSUE TITLE
Processing Labeled 

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#79]

**Comment by verpeutlab** [comment]
Hello, I am currently working on training or fine-tuning DANNCE to a new environment by hand-labeling the frames with Label3D. When I save the labeled frames generated by the GUI that appears when example.m is run, a file named 20211107_172742_Label3D.mat is generated. Can you tell me how to process the data in this file after it has been created? I want to know the next steps I need to take to properly train DANNCE and the COMfinder network.

**Comment by diegoaldarondo** [comment]
To generate a file for dannce, you can use `Label3D.exportDannce()`, replacing the word Labed3D with the name of your Label3D instance (usually labelGui, if following the example). If you are not using default camera names `("Camera1", "Camera2"...)` you can pass a cell array of camera names which will help with some Dannce accounting down the line (details are in the docstring). 

The function will open your file system and prompt you to select your project folder, in which it will save a timestamped file of the appropriate format. You can point to this file in your io.yaml for use in Dannce.

**Comment by verpeutlab** [comment]
Thank you for the response! When I tried to use Label3D.exportDannce( ), there was an issue with the GUI that generated the file 20211107_172742_Label3D.mat, which was named in my previous response. It seems to be unable to triangulate the data points, which is causing the error listed below. I also tried this process with markerless_mouse_1 and I got the same error.

Unrecognized method, property, or field 'Intrinsics' for class 'cameraParameters'.

Error in Label3D>@(X)X.Intrinsics (line 624)
             intrinsics = cellfun(@(X) X.Intrinsics, obj.cameraParams,'uni',0);

Error in Label3D/triangulateLabeledPoints (line 624)
             intrinsics = cellfun(@(X) X.Intrinsics, obj.cameraParams,'uni',0);

Error in Label3D/keyPressCallback (line 876)
                        obj.triangulateLabeledPoints(obj.frameInds(obj.frame));

Error in Animator.runAll (line 255)
                    keyPressCallback(h{i},src,event)

Error in Animator>@(src,event)Animator.runAll(h,src,event) (line 227)
                @(src,event) Animator.runAll(h,src,event)), h)
 
Error while evaluating Figure WindowKeyPressFcn.

**Comment by verpeutlab** [comment]
Also, If I do not triangulate, then the values that appear in the field titled data_3D in 20211107_172742_Label3D.mat come up as NaN.

**Comment by diegoaldarondo** [comment]
> Unrecognized method, property, or field 'Intrinsics' for class 'cameraParameters'.

What version of Matlab are you using?
Label3D requires >= 2019b to work on all operating systems. 

> Also, If I do not triangulate, then the values that appear in the field titled data_3D in 20211107_172742_Label3D.mat come up as NaN.

This is expected.
