### ISSUE TITLE
Synchronization 

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#80]
Hi, we will use 6 cameras to record the mouse behaviors. 
our camera resolution is up to 5120*5120 with 60 fps.
but considering the calculation ability and data storage and transfer, we want to reduce the resolution and frame rate.
I would like to ask for your suggestion about the most optimal parameters for the recording and network training.

besides, I wonder about the effect of timestamp deviation. if we cannot trigger at the beginning of recording but collect the timestamp. I found there is ~15ms deviation between the same frame across different cameras. please kindly advise if the deviation of frames has an effect on the network training and prediction. 

Thank you very much.

**Comment by spoonsso** [comment]
5120*5120 is pretty large, and unfortunately much of the additional resolution (depending on how large your FOV is) will be discounted when sampling into 3D volumes. However, 60 fps is good, and I would recommend stay at that framerate if possible. How large is your arena? We normally use at least 1024 pixels to cover an 8 inch arena, and this works well for us. 

~15 ms deviation is not ideal, but it's also not the end of the world, as long as you are sure there is not going to be drift over the course of the recording. You'll have to make use of the `data_frame` arrays inside `label3d_dannce.mat` to encode the temporal offsets in each camera. That is, at absolute time t (aka a single index into the `data_frame` and `data_sampleID` arrays), `data_frame` will contain the corresponding frame index for each camera. For example, if Camera1 is 15 ms (~1 frame) ahead of Camera2, then sync{1}.data_frame[0] == 1 and sync{2}.data_frame[0] == 2. You can calculate these data_frame arrays from the recorded timestamps using `dannce/utils/preprocessData.m` once the timestamps are formatted as in `dannce/utils/exampleMatchedframes.mat`.

**Comment by spoonsso** [comment]
Closing for now. Please re-open if you want to continue the discussion about this.
