### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by diegoaldarondo** [spoonsso/dannce#86]
Can we roll in the `logging` or `absl.logging` modules to better log our debugging print statements? Would help with sharing our log files, and reduce the printed output when not debugging.

**Comment by data-hound** [comment]
Yes, it would be good to have logging statements instead of print statements. For the choice of using absl for logging, it makes sense to add this dependency only if we want to use its unit testing framework as well. Are we considering absl for unit tests as well?

**Comment by diegoaldarondo** [comment]
`absl` is currently required for `cluster/multi_gpu_test.py` and `tests/cli_test.py` on the `as_landing` and `automated_multi_instance_refactor` branches. I don't think either testing suite requires anything from `absl` that isn't supported by `unittest`, so we could just change all references to `absl` to use `unittest` equivalents and skip the added dependency until we need additional `absl` functionality.

**Comment by spoonsso** [comment]
@data-hound any update on this?

**Comment by data-hound** [comment]
The code changes with logging statements are in as_logging. But, they have not been tested, yet. Once I test and verify things are working as expected, it will be good to merge.

**Comment by data-hound** [comment]
I have finished testing the as_logging branch using a dannce-predict run
