### ISSUE TITLE
Calibrating and Labeling Data with a Fisheye Lens Camera

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#88]
Hello! I am generating the intrinsic parameters of the cameras using the MATLAB Camera Calibrator app. One camera I am using has a fisheye lens. I noticed that the camera with a fisheye lens has different intrinsic parameters than a camera without a fisheye lens. Cameras without a fisheye lens have the intrinsic matrix, radial distortion, and tangential distortion. Cameras with a fisheye lens do not have any of these categories, but instead have the following: 
![fisheye_intrinsics](https://user-images.githubusercontent.com/84207044/147905635-5889a4fb-1fb1-410e-92bc-6899c2d879f9.PNG)

Cameras with and without a fisheye lens have a rotation matrix and a translation vector. 

Is there a way for me to generate the camera extrinsics for a camera with a fisheye lens? Thank you.

**Comment by spoonsso** [comment]
Hi! The fisheye camera model is different than the pinhole camera model (we use the latter). The only way to to integrate a fisheye lens would be to introduce new projection and distortion functions in DANNCE. Can you use a different lens? =)
