### ISSUE TITLE
Exporting Labeled Frame Data to DANNCE

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#90]
Hello! I am working to export labeled frame data to DANNCE after labeling frames in the `example.m` in Label3D. In Issue #83 it is instructed that I use the function `Label3D.exportDannce`, along with `labelGui.exportDannce`. I am not sure what the inputs of both of these functions are, but I am getting the following error messages when I use these two functions. 

`Label3D.exportDannce`
The class Label3D has no Constant property or Static method named 'exportDannce'.

`labelGui.exportDannce`
Error using Label3D/exportDannce (line 1242)
Frame numbers for each frame in videos must be provided.
framesToLabel - Vector of frame numbers for each video frame.
labelGui.exportDannce(''framesToLabel'', framesToLabel)

Could you tell me what information I should be inputting so that I can successfully export the Label3D data to DANNCE?

**Comment by diegoaldarondo** [comment]
framesToLabel should be the index of the samples you're feeding to label3D. So if you are using samples 1, 10, and 50, framesToLabel is [1, 10, 50]. If you're just taking the first 100 samples, it is 1:100. I often use samples `1:100:10000` to have them more separated in time. 

A point of clarification, framesToLabel should be of length size(videos{1}, 4). Its not the indices of the samples you end up labeling, but rather the samples of all of the frames you've given l3d.
