### ISSUE TITLE
why using L-frame as extrinsics calibration

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#94]
Hi.
May I ask why you do the camera calibration using the checkboard and L-frame? I wonder if it is enough to just do checkboard calibration. Thank you.

**Comment by diegoaldarondo** [comment]
Yes, checkerboard is sufficient. 

The motion capture system used to collect the Rat7M dataset could be calibrated with an L-frame made of retro reflective markers, so we used that to share the same space between the RGB cameras and the Mocap ones.

**Comment by tzeriver** [comment]
I know this is closed but can someone point me out where I can find example of "just" using the checkerboard to do the calibration? The only example I see in the in the Calibration/ folder is acquire_calibration_3cam_mouse_clean.m, which seems to be using both L-frame & checkerboard?

Thanks in advance.
