### ISSUE TITLE
Allocated resource in sbatch file

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#99]
Hi, thank you for providing the slurm files for us.
I would like to ask if we want to use 3 GPUs, how to decide the number of nodes and memory and time in the sbatch file? Could please give some suggestions about the allocated resource? Thank you very much!

**Comment by spoonsso** [comment]
I assume this is for training, right? In any case, you shouldn't have to change any of the node or memory values when using multiple GPUs, just use what we have listed for a single GPU.
